Stand_Blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home_app.urls')),
                  path('articles/', include('article_app.urls')),
                  path('accounts/', include('account_app.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'account_app'
urlpatterns = [
    path('contact/', views.ContactUsView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('otp/', views.CheckOtpView.as_view(), name='check_otp'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('verify/email/', views.VerifyEmailView.as_view(), name='verify_email'),
    path('change/password/<token>/', views.ChangePasswordView.as_view(), name='change_password'),

]

home_app/urls.py
from django.urls import path
from . import views

app_name = 'home_app'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

account_app/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.utils.html import format_html


class MyUserManager(BaseUserManager):
    def create_user(self, email, full_name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            full_name=full_name

        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, full_name, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            full_name=full_name,

            password=password,

        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True,
    )
    image = models.ImageField(default='user/image/default_user.jpg', upload_to='user/image')
    full_name = models.CharField(max_length=35, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['full_name']

    def __str__(self):
        return self.email

    def show_image(self):
        return format_html(f'<img src="{self.image.url}" width="50px" height="50px">')

    show_image.short_description = 'image'

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Otp(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField(max_length=255)
    password = models.CharField(max_length=20)
    randcode = models.CharField(max_length=5)
    token = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username


class Profile(models.Model):
    email_user = models.EmailField(max_length=255)
    token = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.email_user

account_app/forms.py
from django import forms

from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError

from account_app.models import User


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""

    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation", widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ["email", 'full_name']

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    disabled password hash display field.
    """

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ["email", "full_name", "image", "password", "is_active", "is_admin"]


class ContactUsForm(forms.Form):
    subject = forms.CharField(max_length=50, widget=forms.TextInput({'placeholder': 'subject'}))
    message = forms.CharField(widget=forms.Textarea({'placeholder': 'message'}))


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput({'placeholder': 'Email'}))
    password = forms.CharField(max_length=20, widget=forms.PasswordInput({'placeholder': 'Password'}))


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50, widget=forms.TextInput({'placeholder': 'username'}))
    email = forms.EmailField(widget=forms.EmailInput({'placeholder': 'email'}))
    password = forms.CharField(max_length=20, widget=forms.PasswordInput({'placeholder': 'password'}))


class OtpForm(forms.Form):
    randcode = forms.CharField(max_length=5, widget=forms.TextInput({'placeholder': 'code'}))


class VerifyEmailForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput({'placeholder': 'email'}))


class ChangePasswordForm(forms.Form):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput({'placeholder': 'new password'}))
    confirmation_password = forms.CharField(max_length=20,
                                            widget=forms.PasswordInput({'placeholder': 'confirmation password'}))

account_app/views.py
import random
import uuid

from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404, Http404, HttpResponse
from django.views import View

from . import forms
from django.views.generic import FormView
from . import models
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin


class ContactUsView(LoginRequiredMixin, FormView):
    template_name = 'account_app/contact.html'
    form_class = forms.ContactUsForm
    success_url = '/'

    def form_valid(self, form):
        email = self.request.user.email
        subject = form.cleaned_data['subject']
        message = form.cleaned_data['message']
        message = message + '/' + email
        send_mail(subject, message, 'rezasharafdini973@gmail.com', ['rezasharafdini973@gmail.com'], fail_silently=False)
        return super().form_valid(form=form)

    def form_invalid(self, form):
        messages.error(self.request, 'The email was not sent')
        return self.render_to_response(self.get_context_data(form=form))


class AboutView(View):
    def get(self, request):
        return render(request, 'account_app/about.html', {})


class LoginView(View):
    def get(self, request):
        if self.request.user.is_authenticated:
            return redirect('/')
        form = forms.LoginForm()
        return render(request, 'account_app/login.html', {'form': form})

    def post(self, request):
        form = forms.LoginForm(request.POST)
        next_page = request.GET.get('next')
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['email'], password=cd['password'])
            if user:
                login(request, user)
                if next_page:
                    return redirect(next_page)

                return redirect('/')
            form.add_error('email', 'user of email invalid.')
        form.add_error('email', 'email or password is wrong.')
        return render(request, 'account_app/login.html', {'form': form})


class RegisterView(View):
    def get(self, request):
        if self.request.user.is_authenticated:
            return redirect('/')
        form = forms.RegisterForm()
        return render(request, 'account_app/register.html', {'form': form})

    def post(self, request):
        form = forms.RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data

            if models.User.objects.filter(email=cd['email']):
                messages.error(request, 'email valid.')
                return render(request, 'account_app/register.html', {'form': form})

            if models.User.objects.filter(full_name=cd['username']):
                messages.error(request, 'username valid.')
                return render(request, 'account_app/register.html', {'form': form})

            token = str(uuid.uuid4())
            randcode = random.randint(10000, 99999)
            print(randcode)
            send_mail('code', str(randcode), 'rezasharafdini973@gmail.com', [cd['email']], fail_silently=False)
            self.request.session['token'] = token
            models.Otp.objects.create(username=cd['username'], email=cd['email'], password=cd['password'],
                                      randcode=randcode, token=token)
            return redirect('account_app:check_otp')


class CheckOtpView(View):
    def get(self, request):
        if not self.request.session.get('token'):
            return redirect('account_app:register')
        form = forms.OtpForm()
        return render(request, 'account_app/otp.html', {'form': form})

    def post(self, request):
        form = forms.OtpForm(request.POST)
        if form.is_valid():
            randcode = form.cleaned_data['randcode']
            try:
                token = self.request.session.get('token')
                otp = models.Otp.objects.get(token=token,randcode=randcode)

                user = models.User.objects.create_user(email=otp.email, full_name=otp.username)
                user.set_password(otp.password)
                user.save()

                self.request.session['token'] = None
                self.request.session.modified = True
                otp.delete()

                login(request, user)
                return redirect('/')


            except:
                messages.error(request, 'please enter  code')
                return render(request, 'account_app/otp.html', {'form': form})

        messages.error(request, 'code is wrong.')
        return render(request, 'account_app/otp.html', {'form': form})


class VerifyEmailView(View):
    def get(self, request):
        if self.request.user.is_authenticated:
            return render('/')
        form = forms.VerifyEmailForm()
        return render(request, 'account_app/verify_email.html', {'form': form})

    def post(self, request):
        form = forms.VerifyEmailForm(request.POST)
        if form.is_valid():
            token = str(uuid.uuid4())
            email = form.cleaned_data['email']

            user = models.User.objects.filter(email=email).first()
            if user:
                models.Profile.objects.create(email_user=email, token=token)
                send_mail('Change Password',
                          f'for change password click on link:http://127.0.0.1:8000/accounts/change/password/{token}/',
                          'rezasharafdini973@gmail.com', [email], fail_silently=False)
                messages.success(request, 'send email')
            else:
                messages.error(request, 'email valid.')
        else:
            messages.error(request, 'email ')

        return render(request, 'account_app/verify_email.html', {'form': form})


class ChangePasswordView(View):
    def get(self, request, token):
        try:
            models.Profile.objects.get(token=token)
            form = forms.ChangePasswordForm()
            return render(request, 'account_app/change_password.html', {'form': form})
        except:
            raise Http404('page not found.')

    def post(self, request, token):
        form = forms.ChangePasswordForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            confirmation_password = form.cleaned_data['confirmation_password']

            try:

                profile = models.Profile.objects.get(token=token)
                if password != confirmation_password:
                    messages.error('password and confirmation password is not same.')
                    return render(request, 'account_app/change_password.html', {'form': form})

                user = models.User.objects.get(email=profile.email_user)
                profile.delete()

                user.set_password(password)
                user.save()
                return redirect('account_app:login')
            except:
                raise Http404('page not found.')

        messages.error(request, 'please again enter password')
        return render(request, 'account_app/change_password.html', {'form': form})

account_app/templates/account_app/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}About Us{% endblock %}

{% block icon %}
    <link rel="icon" href="{% static 'images/about-us.jpg' %}">
{% endblock %}

{% block content %}

    <!-- Page Content -->



    <section class="about-us" style="margin-top: 0">
        <div class="container">

            <div class="row" >
                <div style="margin-top: 80px" class="col-lg-12">
                    <img src="assets/images/about-us.jpg" alt="">
                    <p>Please tell your friends about TemplateMo website. Thank you. You can browse through different
                        categories of templates such as <a rel="nofollow" href="https://templatemo.com/tag/business"
                                                           target="_parent">business</a>, <a rel="nofollow"
                                                                                             href="https://templatemo.com/tag/portfolio"
                                                                                             target="_parent">portfolio</a>,
                        <a rel="nofollow" href="https://templatemo.com/tag/restaurant" target="_parent">restaurant</a>,
                        etc. Pellentesque quis luctus libero. Maecenas pretium molestie erat, ac tincidunt leo gravida
                        ac. Cras ullamcorper eu ipsum eu sollicitudin. Fusce vitae commodo turpis. Integer ullamcorper
                        purus nec justo mollis fermentum. Nunc imperdiet erat nec lacinia laoreet. <br><br>Maecenas
                        faucibus ullamcorper felis vitae finibus. Nullam at quam ut lacus aliquam tempor vel sed ipsum.
                        Donec pellentesque tincidunt imperdiet. Mauris sit amet justo vulputate, cursus massa congue,
                        vestibulum odio. Aenean elit nunc, gravida in erat sit amet, feugiat viverra leo. Phasellus
                        interdum, diam commodo egestas rhoncus, turpis nisi consectetur nibh, in vehicula eros orci vel
                        neque.</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-6">
                    <h4>Two-One Donec porttitor augue</h4>
                    <p>Quisque bibendum cursus viverra. Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum
                        ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
                </div>
                <div class="col-lg-6">
                    <h4>Two-Two Donec porttitor augue</h4>
                    <p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel
                        volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <h4>1-03 Donec porttitor augue</h4>
                    <p>Quisque bibendum cursus viverra. Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum
                        ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
                </div>
                <div class="col-lg-4 col-md-6">
                    <h4>2-03 Donec porttitor augue</h4>
                    <p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel
                        volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
                </div>
                <div class="col-lg-4">
                    <h4>3-03 Donec porttitor augue</h4>
                    <p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel
                        volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
                </div>
            </div>


            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <h4>01 Four Columns</h4>
                    <p>Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at
                        metus sit amet nunc dapibus posuere.</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4>02 Four Columns</h4>
                    <p>Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel
                        tellus semper interdum et id sapien.</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4>03 Four Columns</h4>
                    <p>Morbi ac interdum metus. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel
                        tellus semper interdum et id sapien.</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4>04 Four Columns</h4>
                    <p>Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel
                        tellus semper interdum et id sapien.</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12">
                    <ul class="social-icons">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-behance"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>


        </div>
    </section>



{% endblock %}

account_app/templates/account_app/change_password.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Change Password</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static '/images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'account_app/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'account_app/fonts/iconic/css/material-design-iconic-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/css/main.css' %}">
    <!--===============================================================================================-->
</head>
<body>

<div class="limiter">
    <div class="container-login100" style="background-image: url({% static 'account_app/images/bg-01.jpg' %});">
        <div class="wrap-login100">
            <form class="login100-form validate-form" method="post">
                {% csrf_token %}
                <span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

                <span class="login100-form-title p-b-34 p-t-27">
						Register
					</span>


                {% for message in messages %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% endfor %}

                <div class="wrap-input100 validate-input" data-validate="Enter username">
                    {{ form.password| append_attr:'class:input100' }}
                    <span class="focus-input100" data-placeholder="&#xf207;"></span>
                </div>
                <div class="wrap-input100 validate-input" data-validate="Enter username">
                    {{ form.confirmation_password| append_attr:'class:input100' }}
                    <span class="focus-input100" data-placeholder="&#xf207;"></span>
                </div>


                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        Submit
                    </button>
                </div>

            </form>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'account_app/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'account_app/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/js/main.js' %}"></script>

</body>
</html>

account_app/templates/account_app/login.html
{% load static %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static '/images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/bootstrap/css/bootstrap.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'account_app/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'account_app/fonts/iconic/css/material-design-iconic-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/animsition/css/animsition.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/vendor/daterangepicker/daterangepicker.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'account_app/css/main.css' %}">
    <!--===============================================================================================-->
</head>
<body>

<div class="limiter">
    <div class="container-login100" style="background-image: url({% static 'account_app/images/bg-01.jpg' %});">
        <div class="wrap-login100">
            <form class="login100-form validate-form" method="post">
                {% csrf_token %}
                <span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

                <span class="login100-form-title p-b-34 p-t-27">
						Log in
					</span>

                <div class="wrap-input100 validate-input" data-validate="Enter username">
                    {{ form.email| append_attr:'class:input100' }}
                    <span class="focus-input100" data-placeholder="&#xf207;"></span>
                </div>

                <div class="wrap-input100 validate-input" data-validate="Enter password">
                    {{ form.password| append_attr:'class:input100' }}
                    <span class="focus-input100" data-placeholder="&#xf191;"></span>
                </div>

                <div class="contact100-form-checkbox">
                    <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                    <label class="label-checkbox100" for="ckb1">
                        Remember me
                    </label>
                </div>

                <div class="container-login100-form-btn">
                    <button class="login100-form-btn">
                        Login
                    </button>
                </div>

                <div class="text-center p-t-90">
                    <a class="txt1" href="{% url 'account_app:verify_email' %}">
                        Forgot Password?
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>


<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'account_app/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'account_app/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account_app/js/main.js' %}"></script>

</body>
</html>