Stand_Blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home_app.urls')),
                  path('articles/', include('article_app.urls')),
                  path('accounts/', include('account_app.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'account_app'
urlpatterns = [
    path('contact/', views.ContactUsView.as_view(), name='contact'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('otp/', views.CheckOtpView.as_view(), name='check_otp'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('verify/email/', views.VerifyEmailView.as_view(), name='verify_email'),
    path('change/password/<token>/', views.ChangePasswordView.as_view(), name='change_password'),

]

article_app/urls.py
from django.urls import path
from . import views

app_name = 'article_app'
urlpatterns = [
    path('detail/<str:slug>/', views.ArticleDetailView.as_view(), name='detail'),
    path('list/', views.ArticleListView.as_view(), name='list'),
    path('add/comment', views.AddCommentView.as_view(), name='add_comment')
]

home_app/urls.py
from django.urls import path
from . import views

app_name = 'home_app'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home')
]

templates/includes/all_categories.html
<ul>
    {% for category in all_categories %}
        <li><a href="{% url 'article_app:list' %}?category={{ category.name }}">- {{ category.name }}</a></li>
    {% endfor %}

</ul>

templates/includes/bootstrap.html
{% load static %}


<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Additional Scripts -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/1.5.1/axios.min.js"
        integrity="sha512-emSwuKiMyYedRwflbZB2ghzX8Cw8fmNVgZ6yQNNXXagFzFOaQmbvQ1vmDkddHjm5AITcBIZfC7k4ShQSjgPAmQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script language="text/Javascript">
    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
    function clearField(t) {                   //declaring the array outside of the
        if (!cleared[t.id]) {                      // function makes it static and global
            cleared[t.id] = 1;  // you could use true and false, but that's more typing
            t.value = '';         // with more chance of typos
            t.style.color = '#fff';
        }
    }
</script>

templates/includes/footer.html
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <ul class="social-icons">
                <li><a href="#">Facebook</a></li>
                <li><a href="#">Twitter</a></li>
                <li><a href="#">Behance</a></li>
                <li><a href="#">Linkedin</a></li>
                <li><a href="#">Dribbble</a></li>
            </ul>
        </div>
        <div class="col-lg-12">
            <div class="copyright-text">
                <p>Copyright 2020 Stand Blog Co.

                    | Design: <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a></p>
            </div>
        </div>
    </div>
</div>

templates/includes/head.html
{% load static %}


<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="TemplateMo">
<link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
      rel="stylesheet">


<!-- Bootstrap core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">


<!-- Additional CSS Files -->
<link rel="stylesheet" href="{% static 'css/fontawesome.css' %}">
<link rel="stylesheet" href="{% static 'css/templatemo-stand-blog.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.css' %}">

templates/includes/links_header.html
<div class="container" style="margin-top: 0">
    <a class="navbar-brand" href="{% url 'home_app:home' %}"><h2>Stand Blog<em>.</em></h2></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
            aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                <a class="nav-link " href="{% url 'home_app:home' %}">Home
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == 'about' %}active{% endif %}">
                <a class="nav-link" href="{% url 'account_app:about' %}">About Us</a>
            </li>
            <li class="nav-item  {% if request.resolver_match.url_name == 'list' %}active{% endif %}">
                <a class="nav-link" href="{% url 'article_app:list' %}">Blog Entries</a>
            </li>
            <li class="nav-item  {% if request.resolver_match.url_name == 'detail' %}active{% endif %}">
                <a class="nav-link" href="{% url 'article_app:detail' first_article.slug %}">Post Details</a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
                <a class="nav-link" href="{% url 'account_app:contact' %}">Contact Us</a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">My
                        Account
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">

                        {% if request.user.is_authenticated %}
                            <a href="" class="dropdown-item" type="button">Profile</a>
                            <a href="{% url 'account_app:logout' %}" class="dropdown-item" type="button">Logout</a>

                        {% else %}
                            <a href="{% url 'account_app:login' %}" class="dropdown-item" type="button">Sign in</a>
                            <a href="{% url 'account_app:register' %}" class="dropdown-item" type="button">Sign up</a>

                        {% endif %}
                    </div>
                </div>
            </li>
        </ul>
    </div>
</div>

templates/includes/recent_posts.html
<ul>
    {% for article in recent_article %}
        <li><a href="{% url 'article_app:detail' article.slug %}">
            <h5>{{ article.title }}</h5>
            <span>{{ article.created_at }}</span>
        </a></li>
    {% endfor %}

</ul>